dist: trusty
language: php
php:
  - 7.2
  - 7.4
  - hhvm
services:
  - mysql
  - memcached
env: TMPDIR=/tmp
before_install:
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres
install:
 - composer install --no-interaction --prefer-source --dev
 - phpenv rehash
before_script: 
  - phpenv config-add tests/php7_config.ini
  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php
script:
 - cd tests/
 - php runalltests.php
matrix:
  allow_failures:
   - php: hhvm
