language: php

php:
  - 5.6
  - 7.2
  - hhvm

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached
  - mysql
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10

before_script:
  - phpenv config-rm xdebug.ini || return 0
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" == "7" ]]; then phpenv config-add tests/php7_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php

matrix:
  allow_failures:
   - php: hhvm
