language: php

php:
  - 5.6
  - 7.2
  - hhvm

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached
  - mysql
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10

before_script:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then phpenv config-add tests/config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7" ]]; then phpenv config-add tests/php7_config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then phpenv config-add tests/php72_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php

matrix:
  allow_failures:
   - php: hhvm
